apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: huz0jbb77-python
  janus-idp.io/tekton: huz0jbb77-python
  backstage.io/kubernetes-id: huz0jbb77-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: huz0jbb77-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
