apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: huz0jbb77-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: huz0jbb77-python 
  name: huz0jbb77-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: huz0jbb77-python 
